name: calculate-duplex-metrics
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base =4.4.1
  - r-argparse
  - r-data.table
  - r-magrittr
  - r-seqinr
  - bioconductor-rsamtools
  - bioconductor-biostrings
  - bioconductor-genomicranges
  - bioconductor-iranges
  - r-testthat